parse_config:
  zmk_additional_includes:
    - config/miryoku
  raw_binding_map:
    "&u_to_U_BASE": "Base"
    "&u_to_U_EXTRA": "Extra"
    "&u_to_U_TAP": "Tap"
    "&u_to_U_BUTTON": "Button"
    "&u_to_U_NAV": "Nav"
    "&u_to_U_MOUSE": "Mouse"
    "&u_to_U_MEDIA": "Media"
    "&u_to_U_NUM": "Num"
    "&u_to_U_SYM": "Sym"
    "&u_to_U_FUN": "Fun"
    "&u_bootloader": "Boot"
    "&bootloader": "Boot"
    "&u_bt_sel_0": "BT 0"
    "&u_bt_sel_1": "BT 1"
    "&u_bt_sel_2": "BT 2"
    "&u_bt_sel_3": "BT 3"
    "&u_out_tog": "OUT TOG"
    "&u_caps_word": "CAPS\nWORD"
    "&u_rgb_tog": "RGB\nTOG"
    "&u_rgb_eff": "RGB\nEFF"
    "&u_rgb_hui": "RGB\nHUI"
    "&u_rgb_sai": "RGB\nSAI"
    "&u_rgb_bri": "RGB\nBRI"
    "&u_ep_tog": "EP TOG"
    "&mmv MOVE_UP": "Mouse↑"
    "&mmv MOVE_DOWN": "Mouse↓"
    "&mmv MOVE_LEFT": "Mouse←"
    "&mmv MOVE_RIGHT": "Mouse→"
    "&msc SCRL_UP": "Scrl↑"
    "&msc SCRL_DOWN": "Scrl↓"
    "&msc SCRL_LEFT": "Scrl←"
    "&msc SCRL_RIGHT": "Scrl→"

draw_config:
  key_h: 56
  key_w: 56
  split_gap: 30

